// 読みもの（setup.html の「滑る日・調整」「道具」「上達」「準備・手入れ」「用語・FAQ」）。setup.js より前に読み込む。
// grade: A=物理・幾何 / B=業界の慣習・複数ソース一致・公的な情報 / C=推定・未確定・ソースが割れる。sources は根拠のURL。
globalThis.SETUP_CONTENT = {
  ride: {
    checklists: [
      { id: "bring", title: "持ち物（出発前）", items: [
        "板（流れ止めを付けて）とブーツ",
        "#3のプラスドライバー（持ち歩ける物）",
        "取り付けシート（印刷、またはスマホに保存）",
        "ヘルメット・手首ガード・おしりパッド",
        "ゴーグル・グローブ・ネックウォーマー",
        "日焼け止め・リップ",
        "ワイヤーロック（休憩中の盗難対策）",
        "簡易ワックス（ペーストかスプレー）とコルク",
      ] },
      { id: "before", title: "滑る前のチェック", items: [
        "流れ止めをバインディングと足につないだ",
        "ディスクのネジ（片足4本）が手で回らない",
        "ストラップとラチェットに割れや緩みがない",
        "前傾が設定どおり",
        "BOAは、かかとをブーツの奥に収めてから均一に締めた",
        "トゥストラップがつま先に被さり、甲に乗っていない",
      ] },
      { id: "after", title: "1本目を滑ったあと", items: [
        "ネジの緩みを確認した",
        "かかとの浮き・足の痛み・しびれがない（あればBOAとストラップを見直す）",
        "気になったことを「記録」タブにメモした",
      ] },
      { id: "home", title: "帰ったら", items: [
        "板の水分と汚れを拭き取り、乾かした",
        "ブーツのインナーとインソールを出して乾かした（ストーブ・ドライヤーは使わない）",
        "設定を変えたら「この設定で板に取り付けた」を押した",
        "ソールに芯材まで届く深い傷がないか、エッジにサビがないか見た",
      ] },
    ],
    sections: [
      { id: "leash", title: "流れ止め（リーシュコード）", items: [
        { h: "付けるのが決まり", fig: "leash-why", body: "全国スキー安全対策協議会の「スキー場での行動規則」に「スキーやボードには、流れ止めをつけなければならない」とある。板が斜面を流れると、下にいる人に大けがをさせる。", grade: "B", sources: ["https://www.nikokyo.or.jp/pages/39/"] },
        { h: "種類と付け方", fig: "leash-types", body: "前足の膝下に巻くタイプ、ブーツのひもに付けたリングにフックを掛けるタイプ、BOAのワイヤーを傷めにくい布フックのタイプなどがある。片側をバインディング前足の内側に固定し、板を外すときやコース脇に置くときにも付けておくのが基本。細かい規則はスキー場ごとに違うこともあるので、利用先のルールも確認する。", grade: "B", sources: ["https://allabout.co.jp/gm/gc/214127/"] },
      ] },
      { id: "lift", title: "リフトの乗り降り", items: [
        { h: "前足だけ付ける", fig: "lift-one-foot", body: "リフトに乗るときや短い移動は、前足だけビンディングに付けて後ろ足で蹴って進む（レギュラーは左足）。片足での移動に慣れておくと、降りるのが怖くなくなる。", grade: "B", sources: ["https://www.travel-inn.co.jp/ski/ski-navi/ski-lift-snowboard/"] },
        { h: "乗っている間と降りるとき", fig: "lift-ride", body: "乗っている間は後ろ足で板を支えると前足が楽。降りるときは重心を前にして、足元ではなく前を見る。", grade: "B", sources: ["https://www.travel-inn.co.jp/ski/ski-navi/ski-lift-snowboard/"] },
        { h: "コースの中で座り込まない", fig: "course-edge", body: "行動規則では、コースの中で立ち止まったり座り込んだりしない、転んだら速やかにコースから出る、とされている。ビンディングを付けるのも、降り場から離れたコースの端で。", grade: "B", sources: ["https://www.nikokyo.or.jp/pages/39/"] },
      ] },
      { id: "safety", title: "けがと防具", items: [
        { h: "多いのは腕・肩と頭", fig: "injury-stats", body: "スノーボードで自分から転んだときのけがは、肩を含む腕が69.8%。けがの種類では骨折が45.8%で最も多い。頭のけがはスキー（5.9%）の約2倍の10.9%（全国スキー安全対策協議会 2022/2023シーズン報告）。", grade: "B", sources: ["https://www.caa.go.jp/policies/policy/consumer_safety/caution/caution_074/"] },
        { h: "肩は脱臼、手首は骨折が多い", fig: "injury-body", body: "けがの多い部位は肩・手首・頭・膝・腰の順で、肩の53.8%が脱臼、手首の61.7%が骨折。スノーボーダーのヘルメット装着率は20〜30%程度という学会の解説もある（調査時期は書かれていない）。", grade: "B", sources: ["https://www.jsfr.jp/ippan/condition/ip36.html"] },
        { h: "ヘルメットとプロテクター", fig: "protectors", body: "消費者庁は「ヘルメットやプロテクターを正しく着用しましょう」と呼びかけている。転ぶ回数が多い初心者ほど、ヘルメット・手首ガード・おしりパッドを着ける意味が大きい。", grade: "B", sources: ["https://www.caa.go.jp/policies/policy/consumer_safety/caution/caution_074/"] },
        { h: "防具の選び方", fig: "protector-choose", body: "ヘルメットは頭を強く打ったときの守り、手首ガードは手をついたときに多い手首の骨折の対策、おしりパッドは衝撃を和らげ冷えも防ぐ。サイズや細かい選び方はここでは確認できていないので、ゴーグル・ウェアと合わせて店頭で着けてみて、ずれないものを選ぶ。", grade: "C", sources: ["https://www.ski-ichiba.jp/navi/article/716/"] },
      ] },
      { id: "trouble", title: "ゲレンデで道具が不調になったら", items: [
        { h: "まずコースの端へ", fig: "course-edge", body: "止まって確認するときは、コースの中ではなく端へ移動してから。", grade: "B", sources: ["https://www.nikokyo.or.jp/pages/39/"] },
        { h: "ネジが緩んだ", body: "#3のプラスドライバーで、4本を対角の順に少しずつ均等に締める。サイズの合わないドライバーはネジ頭を傷める。", grade: "B", sources: ["https://www.burton.com/en-us/blogs/the-burton-blog/how-to-mount-snowboard-bindings"] },
        { h: "直せない・けがをした", fig: "patrol", body: "無理に滑り続けず、スキー場のパトロールに連絡する。消費者庁も、用具の調整は信頼できる店舗に頼むよう勧めている。", grade: "B", sources: ["https://www.caa.go.jp/policies/policy/consumer_safety/caution/caution_074/"] },
        { h: "工具とスキー場のサービス", fig: "tools-pocket", body: "ネジは滑っているうちに緩むことがあるので、ドライバーかスノーボード用のマルチツールをポケットに入れておく。スキー場によってはレンタルやショップで締め直しを頼めるが、あるかどうかはスキー場ごとに違うので、行く前に公式サイトで確認する。", grade: "C", sources: [] },
      ] },
      { id: "board-manners", title: "板の置き方・持ち方・盗難対策", items: [
        { h: "止まる場所", fig: "course-blind", body: "コースの真ん中や、上から見えにくい急斜面の下・カーブの先で座り込むと衝突の原因になる。端の見通しの良い場所で止まる。", grade: "C", sources: ["https://allabout.co.jp/gm/gc/214127/"] },
        { h: "板を置くとき", fig: "board-place", body: "流れ止めを付けたまま、ビンディング側を下にして伏せて置くと滑り落ちにくい。ソールを下にして斜面に置くと、そのまま滑り出す。", grade: "C", sources: ["https://allabout.co.jp/gm/gc/214127/"] },
        { h: "持ち方", fig: "board-carry", body: "エッジは鋭いので、人の多い所では体の横で立てて持つ。肩に担ぐと、振り向いたときに後ろの人に当たることがある。電車やバスではボードケースに入れておくと気を使わずに済む。", grade: "C", sources: [] },
        { h: "盗難", fig: "theft-lock", body: "トイレや食事の休憩中に起きやすく、新しいモデルは転売目的で狙われやすいとされる。休憩中はワイヤーロックで柵やラックなど動かない物につなぐ。ステッカーを貼っておくと転売しにくくなり、狙われにくいと言われる。ロックでも完全には防げないので、長く離れない。", grade: "B", sources: ["https://yukinoti-ski.com/snowboard-theft"] },
      ] },
    ],
  },

  gear: {
    sections: [
      { id: "boots-fit", title: "ブーツの合わせ方", items: [
        { h: "かかとを奥に収める", fig: "heel-tap", body: "ブーツを履いたら、かかとを床にトントンと当ててブーツの奥に収めてから締める。", grade: "B", sources: [] },
        { h: "BOAは均一に", fig: "boa-even", body: "すねと足首が均一に包まれるまで締める。締めすぎると足がしびれる。1本滑るとライナーがなじんで緩むことが多いので、締め直す。", grade: "B", sources: [] },
        { h: "かかとが浮くとき", fig: "heel-lift", body: "膝を曲げてもかかとがほとんど浮かないのが目安（6mmほどまでとする解説もある）。浮くなら、BOAを締め直す → アンクルストラップを足首の前に合わせ直す → それでも残るならショップに相談する（熱成形や詰め物など）、の順に試す。", grade: "C", sources: ["https://ridesnowboards.com/en-us/support/how-to-choose-snowboard-boots", "https://www.themountainnerd.com/gear-guides/boots/boot-fit-guide"] },
        { h: "新品がきついのは普通", fig: "break-in", body: "ライナーは使うほど沈むので、はじめはややきつく感じるのが普通とされる。なじむまで合計3〜5日ほどで、最後は1/4サイズほど大きく感じるという目安もある。しびれや強い痛みが続くならショップに相談する。", grade: "B", sources: ["https://ridesnowboards.com/en-us/support/how-to-choose-snowboard-boots", "https://www.themountainnerd.com/gear-guides/boots/boot-fit-guide"] },
        { h: "靴下", fig: "socks", body: "綿や厚すぎる靴下は避け、薄めでフィットする化繊やメリノウールのスノーボード用にする。ブーツを試し履きするときも、滑る日と同じ靴下で。", grade: "B", sources: ["https://www.themountainnerd.com/gear-guides/boots/boot-fit-guide", "https://ridesnowboards.com/en-us/support/how-to-choose-snowboard-boots"] },
        { h: "サイズが合っているかの確かめ方", fig: "shell-fit", body: "ライナーを抜いて靴下でシェルに入り、つま先を前に軽く当てて、かかとの後ろに指が何本入るか見る方法がある。1.5〜2本ほどを目安とする解説がある。ライナーを入れて履いたときは、きつめでも痛くない程度が目安。", grade: "C", sources: ["https://www.themountainnerd.com/gear-guides/boots/boot-fit-guide", "https://ridesnowboards.com/en-us/support/how-to-choose-snowboard-boots"] },
        { h: "BOAの締め方・緩め方", fig: "boa-dial", body: "販売店の説明では、ダイヤルを押し込んで回すと締まり、引き上げると緩む。脱ぐときはダイヤルを引いてからブーツの口を広げると楽。", grade: "B", sources: ["https://www.gearwest.com/products/salomon-w25-faction-boa"] },
      ] },
      { id: "rhythm-fit", title: "RHYTHMをブーツに合わせる", intro: "取り付け手順（「床テスト・取り付け」タブ）の「ブーツに合わせる」の補足。", items: [
        { h: "サイズMの上限", fig: "size-m", body: "サロモン日本公式ではMが26.5〜27.5cm（海外の販売店ではUS6.5〜10とする表もある）。27.5cmは日本公式の表では上限なので、ブーツのかかとがヒールカップの奥に収まるか、ストラップの長さに余裕があるかを最初に確かめる。", grade: "B", sources: ["https://salomon.jp/products/rhythm-rhythm-l476488", "https://www.tactics.com/salomon/rhythm-snowboard-bindings"] },
        { h: "左右を間違えない", fig: "binding-lr", body: "ハイバックとベースが左右非対称なので、逆に付けると足の形に合いにくい。一般にラチェット（バックル）が足の外側に来る向きが目安とされる。本体の左右表記は実物で確かめる。", grade: "C", sources: ["https://salomon.jp/products/rhythm-rhythm-l476488"] },
        { h: "トゥストラップ", fig: "toe-strap", body: "つま先に被せる形（公式の説明は「つま先をカバー」）。長さはMicroMaxで細かく調整できる。一般には、つま先の上側に被せ、ずれて甲に乗らない位置に合わせる。", grade: "B", sources: ["https://salomon.jp/products/rhythm-rhythm-l476488", "https://www.tactics.com/salomon/rhythm-snowboard-bindings"] },
        { h: "アンクルストラップ", fig: "ankle-strap", body: "長さはMicroMaxで微調整できる。締めたときにパッドの中心が足首の前に来るように長さを合わせるのが一般的。", grade: "C", sources: ["https://www.tactics.com/salomon/rhythm-snowboard-bindings", "https://salomon.jp/products/rhythm-rhythm-l476488"] },
        { h: "はみ出しの測り方", fig: "overhang-measure", body: "ブーツを付けた状態で、エッジの真上に定規を垂直に立て、つま先側・かかと側それぞれブーツがどれだけ出ているかを見る。出方がそろうように、バインディングをつま先側・かかと側の方向にずらす。ターンで板を傾けたときにブーツが雪に擦らない程度に収める。", grade: "B", sources: [] },
      ] },
    ],
  },

  care: {
    sections: [
      { id: "preseason", title: "シーズン前の準備（いま〜初滑り）", items: [
        { h: "板のチューンとワックス", fig: "season-plan", body: "シーズンに10回以内なら、シーズン前にショップでチューンしてもらい、あとは簡易ワックスで十分という目安がある。", grade: "B", sources: ["https://dmksnowboard.com/snowboard-wax-frequency/"] },
        { h: "チューンを頼むとき", fig: "craft-bevel", body: "CRAFTは工場出荷で、先端はエッジを丸め（ディチューン）、サイドカットの要所は2°、足の間は3°のベベルになっている。この仕様を伝え、エッジを一律に研がないよう相談する。", grade: "C", sources: ["https://www.bswake.com/products/craft-snowboard"] },
        { h: "防具とブーツ", fig: "protectors", body: "ヘルメットと手首ガードはシーズン前に用意する。ブーツが当たって痛い・かかとが浮くときは、ショップに相談する（FACTION BOAのライナーは熱成形に対応）。", grade: "B", sources: [] },
        { h: "取り付けと床テスト", fig: "floor-test", body: "「床テスト・取り付け」タブで、足形を貼ってしゃがむ床テストをしてから取り付ける。", grade: "C", sources: [] },
      ] },
      { id: "wax", title: "ワックス", items: [
        { h: "頻度の目安", fig: "wax-frequency", body: "シーズン10回以内ならシーズン前後に1回ずつ、20回以上なら月1回＋大事な日の前。", grade: "B", sources: ["https://dmksnowboard.com/snowboard-wax-frequency/"] },
        { h: "切れたサイン", fig: "wax-dry", body: "エッジ付近のソールが毛羽立ってくる。黒いソールは、ワックスが抜けた所が白っぽく見える。", grade: "B", sources: ["https://dmksnowboard.com/snowboard-wax-frequency/"] },
        { h: "CRAFTのソール", fig: "sintered", body: "CRAFTはシンタード（焼結）ソール。ワックスがしみ込みやすいので、こまめにかけるほど滑りを保ちやすい。", grade: "B", sources: ["https://www.bswake.com/products/craft-snowboard"] },
        { h: "簡易ワックス（アイロンなし）", fig: "wax-easy", body: "リムーバーをソールに吹き付けてキッチンペーパーで汚れを拭く → ワックスをソール全体にムラなく塗る（ペーストはコルクで擦り込むと持ちが良い）→ ナイロンブラシで仕上げる。5分ほどで終わるが、効果は数時間ほどと短いので、滑る前や昼休みに塗り直す。", grade: "B", sources: ["https://allabout.co.jp/gm/gc/214094/", "https://skiski.jp/snowcomi/snowboard-wax/"] },
        { h: "ホットワックスの流れ", fig: "wax-hot", body: "汚れを落とす → 専用アイロンで固形ワックスを溶かす → アイロンを止めずに動かして全体に広げる → 10〜20分ほど冷ます → プラスチックのスクレーパーで余分を削る → ナイロンブラシで仕上げる。アイロンを一か所に当て続けるとソールを傷める恐れがある。道具をそろえるまでは、ショップに頼んで普段は簡易ワックスで補う使い分けもできる。", grade: "B", sources: ["https://skiski.jp/snowcomi/snowboard-wax/"] },
      ] },
      { id: "after-ride", title: "滑った後の手入れ", items: [
        { h: "ブーツの乾かし方", fig: "boots-dry", body: "BOAをゆるめ、外せる場合はインナーとインソールを出して分けて乾かす。ストーブやドライヤーの熱は、ソールがはがれたり臭いの原因になったりするので使わない。早く乾かしたいときは新聞紙を詰めて水分を吸わせ、扇風機の風を当てる。インナーを無理に引き抜かない。", grade: "B", sources: ["https://www.snowsheeps.com/snowboard-desiccation/"] },
        { h: "エッジのサビ", fig: "edge-rust", body: "表面の薄いサビは、サビ取り用の消しゴム状の製品でこすると落ちる。中まで入り込んだサビは取れないので、早めに見つけて落とす。落とした後にサビ止めを塗ると予防になる。滑った後に水分を拭いて乾いた場所に置くのも有効と考えられる。", grade: "B", sources: ["https://snowhack.net/archives/19572"] },
        { h: "ソールの深い傷（コアショット）", fig: "coreshot", body: "ソールを貫いて中の芯材まで届いた傷をコアショットと呼ぶ。水がしみ込むと芯材が傷み、板が弱くなる。深い傷や、進行方向を横切る傷は早めの補修が勧められている。芯材が見えるなど不安があれば、自分で直さずショップに相談する。料金の一例は3cmあたり500円〜（税別）、仕上がりまで10日ほどかかる店もある。", grade: "B", sources: ["https://mojane.com/tune-up/sole-repair"] },
      ] },
      { id: "screws", title: "ネジとビンディングの点検", items: [
        { h: "締め方", body: "#3のプラスドライバーで、対角の順に少しずつ均等に締める。電動工具は使わない。", grade: "B", sources: ["https://www.burton.com/en-us/blogs/the-burton-blog/how-to-mount-snowboard-bindings"] },
        { h: "いつ確認するか", fig: "screw-check-timing", body: "取り付けた日は1本目のあとに確認する。そのあとも滑る日ごとに緩みを見る。", grade: "B", sources: ["https://www.burton.com/en-us/blogs/the-burton-blog/how-to-mount-snowboard-bindings"] },
      ] },
      { id: "offseason", title: "シーズン後の保管", intro: "ビンディングを外す前に「取り付けシートを印刷」しておくと、次のシーズンに同じ位置へ戻せる。", items: [
        { h: "手順", fig: "offseason-steps", body: "汚れを落とす → 完全に乾かす → 軽いエッジのサビは専用の消しゴムで落とす → ソールをクリーニング → ワックスを塗り、はがさずにそのまま残す（酸化や汚れを防ぐ）→ ビンディングを外す（難しければネジを少し緩める）。", grade: "B", sources: ["https://dmksnowboard.com/snowboard-off-season-maintenance/"] },
        { h: "置き場所", fig: "storage", body: "温度変化が少なく湿度の低い屋内に、横に寝かせて置く。ベランダ・車内・屋外の物置・完全な密閉・板の上に物を置くのは避ける。", grade: "B", sources: ["https://dmksnowboard.com/snowboard-off-season-maintenance/"] },
      ] },
    ],
  },

  grow: {
    intro: "レッスン1〜5（フォーム分析アプリ）の先を、段階ごとにまとめました。段階3と4は並行して進めてよく、怖くなったら1つ前に戻るのが近道です。セッティングは1回に1か所（角度3°・幅2cm・前傾1段）だけ変え、同じ斜面で2〜3本比べて、合わなければ戻します。",
    current: "s0",
    stages: [
      { id: "s0", fig: "grow-s0", title: "0. 基本姿勢〜緩斜面のS字（レッスン1〜5）", grade: "B",
        goal: "木の葉で止まれて、緩斜面でS字ターンを止まらずにつなげる段階。練習メニューはフォーム分析アプリのレッスンにある。",
        checks: ["緩斜面でS字ターンを止まらずにつなげられる", "行きたい所で止まれる"],
        setting: "S字練習のまま。変えるのは、床テストでNGが出たときか、症状があるときだけ。" },
      { id: "s1", fig: "grow-s1", title: "1. 中斜面の連続ターン（ずらしのターン）", grade: "B",
        goal: "緩斜面のS字を、中斜面でずらしながらの大回り・中回りとしてつなぐ。怖いと後ろ足に乗りがちだが、後ろ足に乗るとかえって加速するので、板が谷を向くにつれて前足に乗せていく。",
        checks: ["中斜面で止まらずに6ターン以上つなげる", "大回りと中回りを滑り分けられる", "行きたい所で止まれる"],
        note: "回数はこのアプリの目安（C）。JSBAバッジテストでは緩斜面のロング/ミドルターン（4級）の次が中斜面（3級）。",
        setting: "基本はS字練習のまま。スピードが上がってヒールサイドでずれて踏ん張れないときだけ、前傾を1段強くする。強くすると足元の遊びがなくなり足が痛くなることもあるので、少しずつ。",
        sources: ["https://www.jsba.or.jp/education/badgetest/", "https://dmksnowboard.com/how-to-turn-on-steep-runs-snowboarding/", "https://www.howtosnowboard.jp/pages/bindingb.html"] },
      { id: "s2", fig: "grow-s2", title: "2. カービングの基礎（ずれを減らす）", grade: "B",
        goal: "ターンは「横ずれ → ずらしのターン → ずれないターン」の順に身につく。ターン後半（山回り）で板を立ててずれを減らすことから始め、最初は緩斜面の浅いターンで板のしなりと反発を感じる。",
        checks: ["S字で好きな場所に行ける（始める目安）", "緩斜面〜中斜面で、ヒール・トゥとも振り返ると細く掘れた跡が残る"],
        setting: "進行方向が見にくい・ターンの入りが遅れるなら前足を+3°（+18°→+21°）。ヒールサイドの跡が太くずれるなら前傾を1段強く（まだなら）。後足はプラス（前向き）にしない。あとで使うスイッチが滑りにくくなるため。",
        sources: ["https://surfsnow.jp/article/howto/snowboard/detail/carvingsnowboard/", "https://www.orion-tour.co.jp/ski/navi/articles/howto/4589", "https://www.travel-inn.co.jp/ski/ski-navi/snowboard-carving-turn/", "https://skiski.jp/snowcomi/snowboard-binding-angle/"] },
      { id: "s3", fig: "grow-s3", title: "3. スイッチ（逆向き）で滑る", grade: "B",
        goal: "180で回ると逆向きで着地することが多く、そのまま滑り続けるにはスイッチが欠かせない。緩斜面でいつもの向きとスイッチを交互に切り替え、怖ければいつもの向きに戻す。",
        checks: ["緩斜面でスイッチの木の葉ができる", "スイッチでS字を3〜4回つなげる"],
        note: "回数はこのアプリの目安（C）。",
        setting: "スイッチで前が見にくいときは、後足を−6°→−9°に3°だけ開く。変えたら床で深くしゃがみ、膝が内に入る・腰がねじれてしんどいなら−6°に戻す。",
        sources: ["https://xn--qck5b4ef.net/guratori-beginner-start-practicing/", "https://rakusnow.com/suittisutannsu-1687"] },
      { id: "s4", fig: "grow-s4", title: "4. プレス・オーリー・ノーリー・180", grade: "B",
        goal: "まず止まった状態や平地で。プレスは力でしならせず重心を移してしならせ、バインディングのすぐ外側に乗り、肩のラインを雪面と平行に保つ。オーリーは後ろ足で踏み切りながら前足を引き上げ、テールの反発で上がる。180は進行方向を向いたまま前後を入れ替えるフロントサイドから。",
        checks: ["平地と緩斜面で、ノーズ・テールとも数秒浮かせて戻れる", "止まった状態→緩斜面のまっすぐ滑りで跳び、着地後もそのまま滑れる", "フロントサイド180で回って、スイッチで滑り出せる"],
        note: "プレスとオーリーのどちらを先に覚えるかは情報源で違うので、並行してよい。「数秒」はこのアプリの目安（C）。",
        setting: "プレスやオーリーがしにくいと感じたら、幅を52→54cm、慣れたら54→56cm（CRAFTの基準幅）と2cmずつ広げる。広げすぎるとオーリーの反発が使いにくく、着地で踏ん張れず、腰や膝の負担も増える。前傾は一番弱くのままの方が脚を動かしやすく、プレスしやすい。",
        safety: "人が少なく広い緩斜面で。リフト乗り場の近く・コースの合流・細い所は避け、後ろから人が来ないか確かめる。この段階の前にヘルメットと手首ガードを用意する。",
        sources: ["https://www.orion-tour.co.jp/ski/navi/articles/howto/1593", "https://www.orion-tour.co.jp/ski/navi/articles/howto/2097", "https://sb-mag.com/ground-trick/", "https://www.howtosnowboard.jp/pages/stancegrotri.html"] },
      { id: "s5", fig: "grow-s5", title: "5. ラントリ入門（滑りながら技を入れる）", grade: "B",
        goal: "中高速で滑りながらトリックを混ぜるスタイルで、中級者以上向けとされる。入り口は、ターンの切り替えでのオーリー/ノーリー、ターン中のプレス、上半身と下半身を逆にひねるリバースターン。自分の力で行う技（オーリーや180）は減速しにくく、ターンの流れを止めにくい。",
        checks: ["中斜面の中くらいの速さで、技のあともターンを3つ以上続けられる"],
        note: "回数はこのアプリの目安（C）。",
        setting: "「ラントリ」プリセット（幅56cm・前足+18°・後足−9°・前傾1段強く）に近づける。段階3・4で後足−9°と幅56cmまで来ていれば、残りは前傾だけ。スピードを上げたときヒールサイドが抜けるなら1段強くする。",
        safety: "技を入れるのは人の少ないコースで。前後左右の距離を十分に取る。",
        sources: ["https://www.sunopino.com/runtrick/", "https://rakusnow.com/ta-nntorikku-15459", "https://skiski.jp/snowcomi/snowboard-binding-angle/"] },
      { id: "s6", fig: "grow-s6", title: "6. グラトリ入門", grade: "C",
        goal: "平地で板の動かし方 → 緩斜面で連続ターン → プレス → オーリー・ノーリー → 180 の順に進める。基本が不十分だと上達が遅れ、けがも増える。練習は荒れていない、雪がほどよくゆるんだ緩斜面で（アイスバーンは転ぶと痛く、荒れたバーンはエッジが引っかかりやすい）。",
        checks: ["フロントサイド・バックサイドの180ができる", "ノーズ・テールのプレスを両方の向きでできる"],
        note: "次へ進む目安はこのアプリ用のまとめ（C）。",
        setting: "「グラトリ」プリセット（幅56cm・±12°）へは、後足−9→−12°、前足+18→+15→+12°と、1日1か所・3°ずつ近づける。前傾は「弱め」とする解説と「きつめ」のライダーがいて情報が割れるので、プレスがしにくいときだけ弱くする。角度を変えるたびに床テストをする。",
        safety: "転ぶと頭と手首を打ちやすい。ヘルメットと手首ガードを着け、人の少ない場所で。",
        sources: ["https://www.orion-tour.co.jp/ski/navi/articles/howto/2097", "https://snowlance.org/ground-trick/ground-trick-for-beginner/", "https://blog.milys-style.com/ground-trick-stance-angle-setup/", "https://www.howtosnowboard.jp/pages/stancegrotri.html"] },
    ],
  },

  glossary: [
    { term: "ノーズ / テール", fig: "g-nose-tail", def: "板の前の先端 / 後ろの先端。CRAFTはノーズ側が実測で8mm長い。" },
    { term: "トゥサイド / ヒールサイド", fig: "g-toe-heel", def: "つま先側のエッジ / かかと側のエッジ。" },
    { term: "有効エッジ", fig: "g-effective-edge", def: "板を平らに置いたとき雪に接するエッジの長さ（接雪点から接雪点まで）。長いほど直進安定とグリップ、短いほど取り回しが軽い。" },
    { term: "サイドカット", fig: "g-sidecut", def: "板の縁のくびれが描く円弧。半径が小さいほど小回りしやすい。ずらさずに板を傾けてたわませて曲がる（カービング）とき、この半径より小さい弧は描けるが、大きい弧は描きにくい。ずらせば大きい弧も描ける。", grade: "A" },
    { term: "キャンバー", fig: "g-camber", def: "真ん中が浮いた反り。踏むと反発とグリップが出る。" },
    { term: "ロッカー", fig: "g-rocker", def: "先端側が持ち上がった反り。回しやすく、引っかかりにくい。" },
    { term: "フラット", fig: "g-flat", def: "反りのない平らな部分。まっすぐ進むときに安定する。" },
    { term: "Rock Out Camber", fig: "g-roc", def: "サロモンの反りの組み合わせ。足の間はフラット、足元はキャンバー、先端はロッカー。" },
    { term: "ディレクショナルツイン", fig: "g-dir-twin", def: "ほぼ前後対称だが、ノーズが少し長い・テールが硬い・足の位置が後ろ寄り、のいずれかで前後差をつけた形。" },
    { term: "スタンス幅", fig: "g-stance-width", def: "前後のバインディングの中心の間隔。" },
    { term: "アングル（角度）", fig: "disc-angle", def: "板の真横を0°として、つま先がノーズ側を向くとプラス、テール側を向くとマイナス。" },
    { term: "ダックスタンス", fig: "g-duck", def: "前足プラス・後足マイナスで、つま先が外に開いた立ち方。スイッチで滑りやすい。" },
    { term: "セットバック", fig: "powder-setback", def: "スタンスの中心を、板の中心からテール側へずらすこと。CRAFTの公表値は0mm。" },
    { term: "インサート", fig: "holes-place", def: "板に埋め込まれたネジ穴。CRAFTは2x4パターン（2列の間4cm・同じ列の穴の間2cm）。片足1列に5個（このアプリの板は実測）。" },
    { term: "ディスク", fig: "g-disc", def: "バインディングの中央の円盤。角度を決めて、4本のネジで板に固定する。" },
    { term: "ハイバック", fig: "g-highback", def: "バインディングのかかと側の背もたれ。ふくらはぎで押して、ヒールサイドのエッジを立てる。" },
    { term: "前傾（フォワードリーン）", fig: "forward-lean", def: "ハイバックを前に倒す量。強いとヒールサイドの反応が速く、弱いと楽で脚を動かしやすい。" },
    { term: "トゥランプ", fig: "toe-ramp", def: "バインディングのつま先の下の台。ブーツのつま先を下から支える。" },
    { term: "カント", fig: "cant", def: "フットベッドの傾き。RHYTHMは2.5°。" },
    { term: "ドラグ", fig: "drag-touch", def: "深く傾けたとき、板からはみ出したブーツが雪に当たって板が持ち上がる現象。", grade: "A" },
    { term: "フレックス", fig: "g-flex", def: "板・ブーツ・バインディングの硬さ。数字はブランドごとの目安で、統一の基準がないため、ほかのブランドの数字とは単純に比べにくい。" },
    { term: "エッジ角", fig: "g-edge-angle", def: "雪面に対して板を傾けた角度。" },
    { term: "逆エッジ", fig: "g-catch-edge", def: "進みたい向きと逆側のエッジが雪に引っかかって、急に転ぶこと。" },
    { term: "スイッチ", fig: "switch-mirror", def: "いつもと逆向き（テールを前）で滑ること。" },
    { term: "レギュラー / グーフィー", fig: "g-regular-goofy", def: "左足が前 / 右足が前。" },
    { term: "ベベル / ディチューン", fig: "g-bevel", def: "エッジの角度の付け方 / エッジの角を丸めて引っかかりにくくすること。" },
    { term: "シンタード", fig: "sintered", def: "焼き固めて作るソール。ワックスがしみ込みやすく、ワックスを保てばよく滑る。" },
    { term: "コアショット", fig: "coreshot", def: "ソールを貫いて中の芯材まで届いた傷。水がしみ込む前に補修する。" },
    { term: "トゥストラップ / アンクルストラップ", fig: "g-straps", def: "つま先を押さえるストラップ / 足首を押さえるストラップ。RHYTHMはどちらもMicroMaxで長さを微調整できる。" },
    { term: "プレス", fig: "press-lever", def: "ノーズかテールに体重を乗せて、板をしならせる技。" },
    { term: "オーリー / ノーリー", fig: "ollie-lever", def: "テール / ノーズを弾いて跳ぶ技。" },
    { term: "ラントリ / グラトリ", fig: "g-runtori-gratri", def: "滑りながら（ターンの中で）入れるトリック / 平らな場所で回ったり弾いたりするトリック。" },
  ],

  faq: [
    { q: "角度のプラス・マイナスはどっち？", fig: "disc-angle", a: "板の真横を0°として、つま先がノーズ側を向くとプラス、テール側を向くとマイナス。後足をマイナスにするとダックスタンスになる。", grade: "B" },
    { q: "ネジはどれくらい締める？", a: "#3のプラスドライバーで、対角の順に少しずつ均等に締める。電動工具は使わない。締めすぎるとインサートを傷めるので、しっかり締まったところで止め、1本目のあとに緩みを確認する。", grade: "B", sources: ["https://www.burton.com/en-us/blogs/the-burton-blog/how-to-mount-snowboard-bindings"] },
    { q: "緩み止めの接着剤（ネジロック剤）は使う？", a: "使う・使わないで意見が分かれ、樹脂の部品を傷めるという話もある。まずは使わず、滑る日ごとに緩みを確認する方が安全。", grade: "C" },
    { q: "自分で取り付けて大丈夫？", a: "このアプリの手順で取り付けられるが、消費者庁は用具の調整は信頼できる店舗に頼むよう勧めている。ネジ穴の状態やつま先・かかとのバランスに不安があれば、ショップで見てもらう。", grade: "B", sources: ["https://www.caa.go.jp/policies/policy/consumer_safety/caution/caution_074/"] },
    { q: "角度を変えたら、何本滑って判断する？", a: "変えた直後の1本は違和感が出やすい。雪の状態や疲れでも感じ方が変わるので、同じ日に何本か滑ってから判断し、「記録」タブに残す。", grade: "B" },
    { q: "左右どちらの足が前か分からない", fig: "g-regular-goofy", a: "決め方には結論が逆になる説が並んでいて、確立した判定法はない。進行方向を見るのに首を無理にひねる・トゥとヒールの上達差が極端・自然に立つと逆向き、のどれかに当てはまるなら、緩斜面で逆向きを試す。", grade: "C" },
    { q: "レンタルの板と感覚が違う", a: "板の長さ・硬さ・反り・セッティングがすべて違うため。まず「S字練習」で慣れ、困ったことがあれば「滑る日・調整」の表で1か所ずつ直す。", grade: "B" },
    { q: "ディスクの溝で動かせる±8mmは確か？", fig: "disc-slot", a: "公表のスタンス幅の範囲と、穴の数・間隔から逆算した推定値。実物のディスクの溝で、どれだけ動くか確かめる。", grade: "C" },
    { q: "BOAのワイヤーが切れたら？", a: "BOAのダイヤルとワイヤーは製品の寿命のあいだ保証され、BOAの保証ページで質問に答えると交換部品を無料で送ってもらえる。日本では購入店に相談するのも手。滑っている最中に切れたら無理をせず、ゆっくり下りる。", grade: "B", sources: ["https://www.boafit.com/en-us/support/warranty"] },
    { q: "新品のブーツが痛いのは普通？", fig: "break-in", a: "はじめにややきついのは普通で、数日でなじむことが多い。しびれや強い痛みが続くなら、サイズや熱成形をショップに相談する。", grade: "B", sources: ["https://ridesnowboards.com/en-us/support/how-to-choose-snowboard-boots", "https://www.themountainnerd.com/gear-guides/boots/boot-fit-guide"] },
  ],

  sources: [
    { label: "スキー場での行動規則（全国スキー安全対策協議会）", url: "https://www.nikokyo.or.jp/pages/39/" },
    { label: "消費者庁 スノースポーツ中の事故に注意", url: "https://www.caa.go.jp/policies/policy/consumer_safety/caution/caution_074/" },
    { label: "日本整形外傷学会 スキーとスノーボードによる外傷", url: "https://www.jsfr.jp/ippan/condition/ip36.html" },
    { label: "DMKsnowboard ワックス頻度", url: "https://dmksnowboard.com/snowboard-wax-frequency/" },
    { label: "DMKsnowboard オフシーズンの保管", url: "https://dmksnowboard.com/snowboard-off-season-maintenance/" },
    { label: "トラベルイン リフトの降り方", url: "https://www.travel-inn.co.jp/ski/ski-navi/ski-lift-snowboard/" },
    { label: "サロモン日本公式 RHYTHM", url: "https://salomon.jp/products/rhythm-rhythm-l476488" },
    { label: "Tactics RHYTHM（仕様）", url: "https://www.tactics.com/salomon/rhythm-snowboard-bindings" },
    { label: "BOA 保証", url: "https://www.boafit.com/en-us/support/warranty" },
    { label: "All About 流れ止めの付け方", url: "https://allabout.co.jp/gm/gc/214127/" },
    { label: "All About 簡易ワックス", url: "https://allabout.co.jp/gm/gc/214094/" },
  ],
};
